version: "3.8"

services:
  base-lottery-fe-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: base-lottery-fe-dev
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    profiles: ["dev"]
    networks:
      - my_local_network

  base-lottery-fe-prod-arm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: base-lottery-fe-prod-arm
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "7866:7866"
    profiles: ["prod"]
    restart: always

    networks:
      - my_local_network

networks:
  my_local_network:
    external: true